---
repos:
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: '2.7.3'
    hooks:
      - id: editorconfig-checker
        alias: ec
  - repo: local
    hooks:
      - id: make-fmt
        name: make fmt
        entry: make fmt
        language: system
        files: \.go$
        pass_filenames: false
      - id: make-vet
        name: make vet
        entry: make vet
        language: system
        files: \.go$
        pass_filenames: false
      - id: make-manifests
        name: make manifests
        entry: make manifests
        language: system
        files: \.go$
        pass_filenames: false
      - id: make-generate
        name: make generate
        entry: make generate
        language: system
        files: \.go$
        pass_filenames: false
