---

name: Prepare IaC toolset
description: Fetches binaries to work with infrastructure

inputs:
  private_key:
    required: true
    description: "ssh private key authorized to pull terraform-modules repo"

runs:
  using: composite
  steps:
    - uses: autero1/action-terragrunt@v3.0.2
      with:
        terragrunt-version: latest
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ inputs.private_key }}
