---

name: Prepare IaC toolset
description: Fetches binaries to work with infrastructure

inputs:
  private_key:
    required: true

runs:
  using: composite
  steps:
    - name: setup kops
      uses: supplypike/setup-bin@v3
      with:
        uri: https://github.com/kubernetes/kops/releases/download/v1.28.0/kops-linux-amd64
        name: kops
        version: v1.28.0
    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v1.1.1
      with:
        terragrunt_version: latest
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ inputs.private_key }}
