---

name: close issue
description: Closes github issue if exists

runs:
  using: composite
  steps:
    - id: parsed
      shell: bash
      run: |
        issue=$(echo $COMMIT_MESSAGE | sed -n 's/.*#\([0-9]*\).*/\1/p')
        echo "issue_number=$issue" >> $GITHUB_OUTPUT
      env:
        COMMIT_MESSAGE: "${{ github.event.head_commit.message }}"
    - if: steps.parsed.outputs.issue_number != ''
      uses: peter-evans/close-issue@v2
      with:
        issue-number: ${{ steps.parsed.outputs.issue_number }}
        comment: >-
          Auto-closing issue at
          ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
