# permissions for end users to edit wireguards.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: wireguard-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: wireguard-operator
    app.kubernetes.io/part-of: wireguard-operator
    app.kubernetes.io/managed-by: kustomize
  name: wireguard-editor-role
rules:
- apiGroups:
  - vpn.ahova.com
  resources:
  - wireguards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vpn.ahova.com
  resources:
  - wireguards/status
  verbs:
  - get
