---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard-operator
  labels:
    app.kubernetes.io/name: wireguard-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: wireguard-operator
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wireguard-operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                    - arm64
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: wireguard-operator
          image: ghcr.io/cornbuddy//wireguard-operator:latest
          imagePullPolicy: IfNotPresent
          args:
            - --leader-elect
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
      serviceAccountName: wireguard-operator
      terminationGracePeriodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: wireguard-operator
spec:
  selector:
    app.kubernetes.io/name: wireguard-operator
  ports:
    - protocol: TCP
      port: 8081
