---
apiVersion: vpn.ahova.com/v1alpha1
kind: Wireguard
metadata:
  name: sample-wg
spec:
  replicas: 1
  network: 192.168.254.1/24
  dropConnectionsTo: []
  serviceType: LoadBalancer
  dns:
    deployServer: false
    address: 10.96.0.1
