---
apiVersion: vpn.ahova.com/v1alpha1
kind: Wireguard
metadata:
  name: wireguard-default
spec:
  replicas: 1

---
apiVersion: vpn.ahova.com/v1alpha1
kind: Wireguard
metadata:
  name: wireguard-internal-dns
spec:
  replicas: 1
  externalDns:
    enabled: false

---
apiVersion: vpn.ahova.com/v1alpha1
kind: Wireguard
metadata:
  name: wireguard-sidecars
spec:
  replicas: 1
  sidecars:
    - name: wireguard-exporter
      image: docker.io/mindflavor/prometheus-wireguard-exporter:3.6.6
      args:
        - "--verbose"
        - "true"
        - "--extract_names_config_files"
        - "/config/wg0.conf"
      volumeMounts:
        - name: wireguard-config
          readOnly: true
          mountPath: /config
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        capabilities:
          add:
            - NET_ADMIN

