---
apiVersion: vpn.ahova.com/v1alpha1
kind: Wireguard
metadata:
  name: wireguard-default
spec:
  replicas: 1

---
apiVersion: vpn.ahova.com/v1alpha1
kind: Wireguard
metadata:
  name: wireguard-internal-dns
spec:
  replicas: 1
  externalDns:
    enabled: false
