---
apiVersion: vpn.ahova.com/v1alpha1
kind: Wireguard
metadata:
  name: wireguard-sample
spec:
  replicas: 1
  network: 192.168.254.1/24
  dropConnectionsTo: []
  serviceType: LoadBalancer
  dns:
    deployServer: false
    address: 10.96.0.1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: karpenter.sh/nodepool
                operator: In
                values:
                  - default
