---
apiVersion: vpn.ahova.com/v1alpha1
kind: Wireguard
metadata:
  name: wireguard-ha
spec:
  address: 192.168.3.1/24
  replicas: 2
  serviceType: LoadBalancer
  serviceAnnotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: udp
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    # default kubelet port
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "10250"
    # using tcp protocol instead of https because I don't want to implement
    # authz for kubelet, I just need some basic health check for nodes
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "tcp"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                  - wireguard-ha

---
apiVersion: vpn.ahova.com/v1alpha1
kind: WireguardPeer
metadata:
  name: peer-ha
spec:
  wireguardRef: wireguard-ha
  address: 192.168.3.2/32
