---

name: Acceptance tests
on:
  pull_request:
    branches: [main]
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types: [submitted]
  check_suite:
    types: [completed]

concurrency:
  group: "acceptance-${{ github.event.repository.name }}"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: run smoke tests
        run: make smoke

  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - uses: thollander/actions-comment-pull-request@v2
        with:
          message: "/fast-forward"
          GITHUB_TOKEN: "${{ secrets.PAT_TOKEN }}"

  close-issue:
    name: Close issue
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - name: Parse issue from commit message
        id: parsed
        run: |
          issue=$(echo $COMMIT_MESSAGE | sed -n 's/.*#\([0-9]*\).*/\1/p')
          echo "issue_number=$issue" >> $GITHUB_OUTPUT
        env:
          COMMIT_MESSAGE: "${{ github.event.head_commit.message }}"
      - name: Close Issue
        if: steps.parsed.outputs.issue_number != ''
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ steps.parsed.outputs.issue_number }}
          comment: >-
            Auto-closing issue at
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
