---
name: Acceptance tests
on:
  workflow_run:
    workflows: ["Commit checks"]
    branches: [develop]
    types:
      - completed


concurrency:
  group: "deployment-pipeline-${{ github.event.repository.name }}"

env:
  TEST_CLUSTER_NAME: test
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  prepare-env:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'
          check-latest: true
      - run: aws eks update-kubeconfig --name $TEST_CLUSTER_NAME
      - name: calculate tag for docker image
        uses: mathieudutour/github-tag-action@v6.1
        id: tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
      - run: make deploy
        env:
          IMG_BASE: >-
            478845996840.dkr.ecr.eu-central-1.amazonaws.com/wireguard-operator
          TAG: ${{ steps.tag.outputs.previous_tag }}

  acceptance:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs:
      - prepare-env
    steps:
      - uses: actions/checkout@v4
      - run: aws eks update-kubeconfig --name $TEST_CLUSTER_NAME
      - run: make smoke

  clean-env:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} && always()
    needs:
      - acceptance
    steps:
      - uses: actions/checkout@v4
      - run: aws eks update-kubeconfig --name $TEST_CLUSTER_NAME
      - run: make undeploy

  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs:
      - acceptance
    steps:
      - uses: actions/checkout@v4
      - name: get PR number
        id: pr
        run: |
          echo "PR_NUMBER=$(gh pr view develop --json number --jq)"
          >> $GITHUB_OUTPUT
      - uses: thollander/actions-comment-pull-request@v2
        with:
          message: "/fast-forward"
          pr_number: "${{ steps.pr.outputs.PR_NUMBER }}"
          GITHUB_TOKEN: "${{ secrets.PAT_TOKEN }}"

  close-issue:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs:
      - acceptance
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/close-issue
