---
name: Acceptance tests
on:
  pull_request:
    types: [labeled]

concurrency:
  group: "acceptance-${{ github.event.repository.name }}"

env:
  TEST_CLUSTER_NAME: test
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  disapprove-pull-request:
    name: Remove pull request approval if exists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: >-
          gh pr review "${{ github.event.number }}"
          --request-changes
          --body "waiting tests to succeed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  prepare-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'
          check-latest: true
      - run: aws eks update-kubeconfig --name $TEST_CLUSTER_NAME
      - run: kubectl get no
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: latest-tag
        with:
          semver_only: false
      - run: make deploy
        env:
          IMG_BASE: >-
            478845996840.dkr.ecr.eu-central-1.amazonaws.com/wireguard-operator
          TAG: ${{ steps.latest-tag.outputs.tag }}

  acceptance:
    runs-on: ubuntu-latest
    needs:
      - prepare-env
    steps:
      - uses: actions/checkout@v4
      - run: aws eks update-kubeconfig --name $TEST_CLUSTER_NAME
      - run: make smoke

  approve-pull-request:
    runs-on: ubuntu-latest
    needs:
      - acceptance
    steps:
      - uses: actions/checkout@v4
      - run: gh pr review "${{ github.event.number }}" --approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  clean-env:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - acceptance
    steps:
      - uses: actions/checkout@v4
      - run: aws eks update-kubeconfig --name $TEST_CLUSTER_NAME
      - run: make undeploy
      - run: gh pr edit ${{ github.event.number }} --remove-label "help wanted"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  release:
    runs-on: ubuntu-latest
    needs:
      - acceptance
    steps:
      - uses: actions/checkout@v4
      - uses: thollander/actions-comment-pull-request@v2
        with:
          message: "/fast-forward"
          GITHUB_TOKEN: "${{ secrets.PAT_TOKEN }}"

  close-issue:
    runs-on: ubuntu-latest
    needs:
      - acceptance
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/close-issue
