---
name: acceptance tests
on: pull_request

concurrency:
  group: "acceptance-${{ github.event.repository.name }}"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  disapprove-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: >-
          gh pr review "${{ github.event.number }}"
          --request-changes
          --body "waiting tests to succeed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  acceptance:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/cornbuddy/${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-go@v3
        with:
          check-latest: true
      - run: aws eks update-kubeconfig --name $TEST_CLUSTER_NAME
      - run: kubectl get no
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: latest-tag
        with:
          semver_only: false
      - run: make deploy
        env:
          TAG: ${{ steps.latest-tag.outputs.tag }}
      - run: make smoke

  approve-pull-request:
    runs-on: ubuntu-latest
    needs:
      - acceptance
    steps:
      - uses: actions/checkout@v4
      - run: gh pr review "${{ github.event.number }}" --approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  clean:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - acceptance
    steps:
      - uses: actions/checkout@v4
      - run: make clean
