---
name: Perform CI develop
on:
  push:
    branches:
      - develop
      - main
concurrency:
  group: "ci-${{ github.event.repository.name }}-${{ github.ref }}"
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          update-environment: false
      - name: Install editorchecker
        run: pip install editorconfig-checker
      - name: Lint commit
        uses: wagoid/commitlint-github-action@v4
      - name: Run pre-commit git hooks
        uses: pre-commit/action@v3.0.0
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare golang
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'
          check-latest: true
      - run: make vet
      - run: make build
      - run: make test
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    needs:
      - lint
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Prepare buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Calculate tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token:  ${{ secrets.GITHUB_TOKEN }}
          release_branches: "main"
          dry_run: true
      - name: Populate image cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ci-wireguard-operator
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Bake test docker image
        run: make docker-buildx
        env:
          IMG: "478845996840.dkr.ecr.eu-central-1.amazonaws.com/wireguard-operator:${{ steps.tag.outputs.new_tag }}"
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: "main"
  pull-request:
    name: Submit pull request
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    needs:
      - lint
      - test
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Auto create pull request
        id: pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: main
      - name: Trigger fast forward
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: "/fast-forward"
          pr_number: ${{steps.pr.outputs.pr_number}}
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

