---
name: commit checks
on:
  push:
    branches:
      - "*"
      - "*/*"
      - "!main"

concurrency:
  group: commit-checks-${{ github.event.repository.name }}-${{ github.ref }}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: stable
          check-latest: true
      - uses: actions/setup-python@v4
        with:
          update-environment: false
      - uses: pre-commit/action@v3.0.0

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: stable
          check-latest: true
      - uses: medyagh/setup-minikube@latest
      - run: make test

  release-candidate:
    runs-on: ubuntu-latest
    needs:
      - pre-commit
      - test
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/release
        id: tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ github.repository }}
          registry: ghcr.io
          prerelease: true

  submit-pull-request:
    runs-on: ubuntu-latest
    permissions: write-all
    needs:
      - release-candidate
    steps:
      - uses: actions/checkout@v4
      - run: >-
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          >> $GITHUB_OUTPUT
        id: extract_branch
      - run: |
          gh pr create \
          --base main \
          --head "${{ steps.extract_branch.outputs.branch }}" \
          --fill-first || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
