---
name: commit checks
on:
  push:
    branches:
      - "*"
      - "*/*"
      - "!main"

concurrency:
  group: "commit-checks-${{ github.event.repository.name }}-${{ github.ref }}"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'
          check-latest: true
      - uses: actions/setup-python@v4
        with:
          update-environment: false
      - uses: pre-commit/action@v3.0.0

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'
          check-latest: true
      - run: go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
      - run: make test

  release-candidate:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - uses: actions/checkout@v4
      - uses: mathieudutour/github-tag-action@v6.2
        id: tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
      - run: make docker
        env:
          IMAGE: ghcr.io/cornbuddy/${{ github.event.repository.name }}
          TAG: ${{ steps.tag.outputs.new_tag }}
