---
name: Commit checks
on:
  push:
    branches:
      - "*"
      - "*/*"
      - "!main"

concurrency:
  group: "commit-checks-${{ github.event.repository.name }}-${{ github.ref }}"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          update-environment: false
      - run: pip install editorconfig-checker
      - uses: wagoid/commitlint-github-action@v4
      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'
          check-latest: true
      - name: Run pre-commit git hooks
        uses: pre-commit/action@v3.0.0

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'
          check-latest: true
      - run: make test

  release:
    name: Release RC
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    needs:
      - lint
      - test
    steps:
      - uses: actions/checkout@v4
      - name: calculate tag for docker image
        uses: mathieudutour/github-tag-action@v6.1
        id: tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: "main"
          dry_run: true
      - uses: ./.github/actions/build
        with:
          version: ${{ steps.tag.outputs.new_tag }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
      - uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.REPO_TOKEN }}
          release_branches: "main"
      - run: >-
          gh pr create
          --base main
          --fill-first
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      - uses: peter-evans/create-pull-request@v5
        with:
          token: "{{ secrets.REPO_TOKEN }}"
          base: "main"
          branch: "${{ github.ref }}"
          assignees: ""
