---

name: Release

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      IMAGE: "478845996840.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/wireguard-operator"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: mathieudutour/github-tag-action@v6.1
        id: tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ahova/infrastructure/.github/actions/docker-buildx@main
        with:
          version: ${{ steps.tag.outputs.new_tag }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
