---
name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: mathieudutour/github-tag-action@v6.1
        id: tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: "main"
      - uses: ./.github/actions/build
        with:
          version: ${{ steps.tag_version.outputs.new_tag }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
